version: '3.1'

services:
  yellr_server:
    image: SUBSTITUTE_RELEASE_IMAGE_NAME_HERE
    command: "/home/elixir/yellr/start_server"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - HOST=SUBSTITUTE_DEPLOY_HOST_NAME_HERE
      - PORT=8080
      - API_KEY=SUBSTITUTE_DEPLOYMENT_API_KEY_HERE
      - GITHUB_API_PAT=SUBSTITUTE_GITHUB_PAT_HERE
    depends_on:
      - db
    links:
      - db
    ports:
      - 9000:8080
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: